### ISSUE TITLE
Question: Would this apply to UB5A?

### ISSUE THREAD

**Issue by Nulled-Out** [tedboudros/tplink-ub500-linux-patch-guide#1]
There seems to be another version for both this and the 4.0 dongle. Only found one mention of them where it was said that they're the same but was never sure. 

Have you been able to tell if there was a change in chipset or firmware or whatever?

**Comment by tedboudros** [comment]
Since I do not have the dongle myself to be able to test this, I am not able to answer you. I would say, if you have the UB5A dongle yourself, go for it and let us all know (you shouldn't cause any other issues elsewhere in your system by following this guide)! :smile:

**Comment by tedboudros** [comment]
This issue seems to be inactive. If any of you guys try this with the UB5A and you're willing to let people know if it works or not, please create a new issue! I am closing this one.
