### ISSUE TITLE
Question : How to Sign the compiled patched file btusb.ko: linux-5.11/drivers/bluetooth and run

### ISSUE THREAD

**Issue by cityji** [tedboudros/tplink-ub500-linux-patch-guide#2]
Hi, There Thanks for sharing this guided readme file really helpful, 
I've to admit i am newbie to linux and this could me my mis understanding,

**I've been able to follow the guides till mid step 3** 
i'm having issues at : Sign the compiled patched file btusb.ko: linux-5.11/drivers/bluetooth and run

i am running this comand : **kmodsign sha512 MOK.priv MOK.der btusb.ko**
at diretory : **/home/noob/Desktop/linux-5.14**

**I'am Getting This Error : **

**MOK.der btusb.ko**
**At main.c:281:**
- **SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69**
- **SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76**
**kmodsign: btusb.ko: No such file or directory**

Shuld i change the current dir?
I wish to know a bit about this section, any help is really appricated :) 

Thanks Again for making this guide 👍🏻

**Comment by tedboudros** [comment]
Sorry for replying so late, you've probably already resolved the issue but in case you haven't;
Try running the commands again inside the `linux-X.XX/drivers/bluetooth` directory as the `cd` command indicates in Step 1
